# Generated by Django 6.1 on 2026-08-13 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Concessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('clientela', models.CharField(blank=True, choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=10)),
                ('forma_filiacao', models.CharField(blank=True, max_length=120)),
                ('ramo_atividade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, db_index=True, max_length=2)),
                ('aps_codigo', models.CharField(blank=True, max_length=20)),
                ('aps_nome', models.CharField(blank=True, max_length=255)),
                ('cid_codigo', models.CharField(blank=True, max_length=10)),
                ('cid_descricao', models.CharField(blank=True, max_length=255)),
                ('despacho_codigo', models.CharField(blank=True, max_length=10)),
                ('despacho_descricao', models.CharField(blank=True, max_length=255)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('qt_sm_rmi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('qt_anos_contribuicao', models.PositiveIntegerField(blank=True, null=True)),
                ('data_dib', models.DateField(blank=True, help_text='Data de Início do Benefício', null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jurimetria.especie')),
            ],
            options={
                'indexes': [models.Index(fields=['competencia', 'uf'], name='jurimetria__compete_08fad2_idx'), models.Index(fields=['competencia', 'especie'], name='jurimetria__compete_58d1cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Indeferimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('clientela', models.CharField(blank=True, choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=10)),
                ('forma_filiacao', models.CharField(blank=True, max_length=120)),
                ('ramo_atividade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, db_index=True, max_length=2)),
                ('aps_codigo', models.CharField(blank=True, max_length=20)),
                ('aps_nome', models.CharField(blank=True, max_length=255)),
                ('motivo', models.CharField(db_index=True, max_length=255)),
                ('data_indeferimento', models.DateField(blank=True, null=True)),
                ('data_der', models.DateField(blank=True, help_text='Data de Entrada do Requerimento', null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jurimetria.especie')),
            ],
            options={
                'indexes': [models.Index(fields=['competencia', 'uf'], name='jurimetria__compete_3e9abb_idx'), models.Index(fields=['competencia', 'especie'], name='jurimetria__compete_c3ab78_idx')],
            },
        ),
    ]
